from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import optimizers

import tensorflow as tf
tf.enable_eager_execution()
from keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

#one hot encoding
y_train_one_hot=tf.keras.utils.to_categorical(y_train,num_classes=10)
y_test_one_hot=tf.keras.utils.to_categorical(y_test,num_classes=10)

#Transofrm them to a float32 type
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

#normalize the images
x_train /= 255
x_test /= 255


def base_model_v2():

    #input_layer = tf.keras.layers.Input(shape=(32, 32, 3), name="input_layer")
    num_classes=10
    weight_decay = 1e-4
    input_shape=x_train.shape[1:]
    #
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Conv2D(32, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), 
                                     input_shape=input_shape))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.Conv2D(32, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2,2)))
    model.add(tf.keras.layers.Dropout(0.2))
 
    model.add(tf.keras.layers.Conv2D(64, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.Conv2D(64, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2,2)))
    model.add(tf.keras.layers.Dropout(0.3))
 
    model.add(tf.keras.layers.Conv2D(128, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.Conv2D(256, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(tf.keras.layers.Activation('elu'))
    model.add(tf.keras.layers.BatchNormalization())
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2,2)))
    model.add(tf.keras.layers.Dropout(0.4))
 
    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))
    
    
    
    return model
 

    
batch_size = 256

epochs = 50
datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True)

datagen.fit(x_train)


cif10=base_model_v2()

#opt_rms=tf.keras.optimizers.RMSprop(lr=0.001,decay=1e-6)

opt=tf.train.AdamOptimizer(learning_rate=0.0001)
cif10.compile(optimizer=opt,loss="categorical_crossentropy", metrics=['accuracy'])


    

#Fit the model on the batches generated by datagen.flow().
history2 = cif10.fit_generator(datagen.flow(x_train, y_train_one_hot,batch_size=batch_size),
                               validation_data=(x_test,y_test_one_hot),epochs=epochs )