import torch.nn as nn

def test_conv_backcompat(self):
          from torch.serialization import SourceChangeWarning
          # This file was generated by running on PyTorch 1.0.1 on Python 2:
          #
          #     import torch
          #     from torch import nn
          #     m = nn.Conv2d(1, 1, 1)
          #     torch.save(m, 'legacy_conv2d.pt')
          #
          path = download_file('https://download.pytorch.org/test_data/legacy_conv2d.pt')
          with warnings.catch_warnings():
              warnings.simplefilter('ignore', SourceChangeWarning)
              m = torch.load(path)
          input = torch.randn((1, 1, 1, 1), dtype=torch.float)
          self.assertEqual(m(input).size(), (1, 1, 1, 1))