import torch
import torch.nn as nn

# traced_model was generated by torch.jit.trace

image = torch.rand((1,3,1024,1024))
torch.onnx.export(traced_model, image, "model.onnx", input_names=input_names, output_names=output_names)

class Concatenate(nn.Module):
    def __init__(self) -> None:
        super().__init__()

        self.linear = nn.Linear(10,10)

    def forward(self, x,y):
        x = self.linear(x)
        y = self.linear(y)
        return torch.concat([x,y], 1)

concatenate_model = Concatenate()
example_input = (torch.rand(1,1,10), torch.rand(1,2,10))

traced_model = torch.jit.trace(concatenate_model, example_input)

torch.onnx.export(traced_model, example_input, "concatenate.onnx", input_names=["x", "y"], output_names=["result"])